<a href="https://colab.research.google.com/github/lejhindary/MedStar-G5/blob/main/MedStarG5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import os

In [3]:
from google.colab import drive
drive.mount('/content/drive')
data_folder = "/content/drive/MyDrive/Group 5: Dereck Kaale/MIMIC-IV-ExtCardiacDiseases/Dataset"
os.listdir(data_folder)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

['heart_diagnoses.csv',
 'heart_diagnoses_all.csv',
 'heart_diagnoses_all_true.csv',
 'heart_procedures.csv',
 'heart_microbiologyevents_first_micro.csv',
 'heart_microbiologyevents.csv',
 'heart_labevents_first_lab.csv',
 'heart_labevents_examination_group.csv',
 'README.md',
 'LICENSE.txt',
 'SHA256SUMS.txt',
 'RAG_data']

In [6]:
heart_diagnoses = pd.read_csv(data_folder+"/heart_diagnoses.csv")
true_heart_diagnoses = pd.read_csv(data_folder+"/heart_diagnoses_all_true.csv")

In [7]:
true_heart_diagnoses.iloc[4]

subject_id                                     10000980
hadm_id                                        26913865
seq_num                                               5
icd_code                                           I348
long_title    Other nonrheumatic mitral valve disorders
Name: 4, dtype: object

In [8]:
true_heart_diagnoses[(true_heart_diagnoses['icd_code']=="I359") | (true_heart_diagnoses['icd_code']=="I350")].value_counts()

#I359 = nonrheumatic aortic valve disorder unspecified
#I350 nonrheumatic aortic valve stenosis
#I348 other nonrheumatic mitral valve disorder

subject_id  hadm_id   seq_num  icd_code  long_title
19965144    28838567  4        I359      Nonrheumatic aortic valve disorder, unspecified    1
10004457    28723315  1        I359      Nonrheumatic aortic valve disorder, unspecified    1
10017886    20015927  6        I359      Nonrheumatic aortic valve disorder, unspecified    1
10035787    29728342  1        I350      Nonrheumatic aortic (valve) stenosis               1
10051074    21350747  8        I350      Nonrheumatic aortic (valve) stenosis               1
                                                                                           ..
10394761    23737808  1        I359      Nonrheumatic aortic valve disorder, unspecified    1
10388470    29742451  4        I350      Nonrheumatic aortic (valve) stenosis               1
10354217    22315422  4        I359      Nonrheumatic aortic valve disorder, unspecified    1
10347400    22934865  14       I359      Nonrheumatic aortic valve disorder, unspecified    1
10285427    28941482  1        I350      Nonrheumatic aortic (valve) stenosis               1
Name: count, Length: 510, dtype: int64

In [15]:
# pulls all icd codes
all_icd = true_heart_diagnoses[['icd_code', 'long_title']].drop_duplicates().sort_values('icd_code').reset_index(drop=True)
# filters vhd related codes
vhd_icd = all_icd[all_icd['long_title'].str.lower().str.contains('valve|rheumatic', na=False) ]
#filters ie related codes
ie_icd = all_icd[all_icd['long_title'].str.lower().str.contains('endocarditis', na=False)]
print(f"Number of VHD ICD codes: {len(vhd_icd)}")
print(vhd_icd.to_string())

print(f"\n Number of IE ICD codes: {len(ie_icd)}")

print(ie_icd.to_string())

Number of VHD ICD codes: 37
     icd_code                                                                  long_title
798      I050                                                   Rheumatic mitral stenosis
799      I051                                              Rheumatic mitral insufficiency
800      I052                                Rheumatic mitral stenosis with insufficiency
801      I060                                                   Rheumatic aortic stenosis
802      I061                                              Rheumatic aortic insufficiency
803      I062                                Rheumatic aortic stenosis with insufficiency
804      I071                                           Rheumatic tricuspid insufficiency
805      I078                                    Other rheumatic tricuspid valve diseases
806      I080                        Rheumatic disorders of both mitral and aortic valves
807      I081                     Rheumatic disorders of both mitral and tricuspid valves
808      I082                     Rheumatic disorders of both aortic and tricuspid valves
809      I083         Combined rheumatic disorders of mitral, aortic and tricuspid valves
810      I088                                     Other rheumatic multiple valve diseases
811     I0981                                                     Rheumatic heart failure
812     I0989                                    Other specified rheumatic heart diseases
813      I099                                        Rheumatic heart disease, unspecified
896      I340                                   Nonrheumatic mitral (valve) insufficiency
897      I341                                        Nonrheumatic mitral (valve) prolapse
898      I342                                        Nonrheumatic mitral (valve) stenosis
899      I348                                   Other nonrheumatic mitral valve disorders
900      I350                                        Nonrheumatic aortic (valve) stenosis
901      I351                                   Nonrheumatic aortic (valve) insufficiency
902      I352                     Nonrheumatic aortic (valve) stenosis with insufficiency
903      I358                                   Other nonrheumatic aortic valve disorders
904      I359                             Nonrheumatic aortic valve disorder, unspecified
905      I361                                Nonrheumatic tricuspid (valve) insufficiency
906      I368                                Other nonrheumatic tricuspid valve disorders
907      I378                                Other nonrheumatic pulmonary valve disorders
908       I38                                             Endocarditis, valve unspecified
1640     M353                                                      Polymyalgia rheumatica
1845     Q221                                         Congenital pulmonary valve stenosis
1847     Q231                                    Congenital insufficiency of aortic valve
2253  T8203XA                        Leakage of heart valve prosthesis, initial encounter
2254  T8209XA  Other mechanical complication of heart valve prosthesis, initial encounter
2640     Z952                                          Presence of prosthetic heart valve
2641     Z953                                           Presence of xenogenic heart valve
2642     Z954                                   Presence of other heart-valve replacement

 Number of IE ICD codes: 2
    icd_code                                 long_title
895     I330  Acute and subacute infective endocarditis
908      I38            Endocarditis, valve unspecified